# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 99c732cf71a9368da110314dc67e728109c5c6609daabde694345c4c8a3438ab20d6fd0148e2d0a7f6651d5ca11e9c1cdb36d6299a9794979fe0f91b19227367

test:
  secret_key_base: 2310dc668b3ad2fec2dbf41f0c011d785d23e657389826db31b6aa11232d4523d05ce48eff1c3010b05093bf9099ad2307e99285b5ddc4074953f75b2ec7ac2a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
